name: clubbar_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.2.2
  mime: ^2.0.0
  http_parser: ^4.0.2
  intl: ^0.20.2
  fl_chart: ^0.68.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true